const IMAGE = {
  ICON_PROFILE: require('../images/icons/profile.png'),
  ICON_MENU: require('../images/icons/menu.png'),
  ICON_BACK: require('../images/icons/back.png'),

  ICON_HOME_B: require('../images/icons/home_b.png'),
  ICON_HOME_W: require('../images/icons/home_w.png'),
  ICON_SETTING_B: require('../images/icons/setting_b.png'),
  ICON_SETTING_W: require('../images/icons/setting_w.png'),
  ICON_LEFT_ARROW: require('../images/icons/left-arrow.png'),
  IMAGE_BACK: require('../images/image/back.jpg'),
  IMAGE_LOGIN: require('../images/image/login2.jpg'),
  IMAGE_GUIDE: require('../images/image/guide.jpg'),
  IMAGE_USER: require('../images/image/user.png'),
  ICON_QUESTION: require('../images/icons/question.png'),
  ICON_MONEY: require('../images/icons/money.png'),
  ICON_GEAR: require('../images/icons/gear.png'),
  ICON_INFO: require('../images/icons/info.png'),
  ICON_COIN: require('../images/icons/coin.png'),
  ICON_BANK: require('../images/icons/bank.png'),
  ICON_LOGOUT: require('../images/icons/logout.png'),

  IMAGE_SLIDE_1: require('../images/image/IMG_2078.jpg'),
  IMAGE_SLIDE_2: require('../images/image/IMG_2082.jpg'),
  IMAGE_SLIDE_3: require('../images/image/IMG_2083.jpg'),
  IMAGE_SLIDE_4: require('../images/image/IMG_2084.jpg'),
  '1': require('../images/image/1.jpg'),
  '2': require('../images/image/2.jpg'),
  '3': require('../images/image/3.jpg'),
  '4': require('../images/image/4.jpg'),
  '5': require('../images/image/5.jpg'),
  '6': require('../images/image/6.jpg'),
  '7': require('../images/image/7.jpg'),
  '8': require('../images/image/8.jpg'),
  '9': require('../images/image/9.jpg'),
  '10': require('../images/image/10.jpg'),
  '11': require('../images/image/11.jpg'),
  '12': require('../images/image/12.jpg'),
  '13': require('../images/image/13.jpg'),
  '14': require('../images/image/14.jpg'),
  '15': require('../images/image/15.jpg'),
  '16': require('../images/image/16.jpg'),
  '17': require('../images/image/17.jpg'),
  '18': require('../images/image/18.jpg'),
  '19': require('../images/image/19.jpg'),
  '20': require('../images/image/20.jpg'),
  '21': require('../images/image/21.jpg'),
  '22': require('../images/image/22.jpg'),
  '23': require('../images/image/23.jpg'),
  '24': require('../images/image/24.jpg'),

  'GTour': require('../PackagePhoto/GTour.jpg'),
  'BTour': require('../PackagePhoto/BTour.jpg'),
  'Dinner': require('../PackagePhoto/Dinner.jpg'),
  'Lunch': require('../PackagePhoto/Lunch.jpg'),
  'food1.jpg': require('../PackagePhoto/food1.jpg'),
  'food2.jpg': require('../PackagePhoto/food2.jpg'),
  'food3.jpg': require('../PackagePhoto/food3.jpg'),

  '7501.jpg': require('../StaffsPhoto/7501.jpg'),
  '7502.jpg': require('../StaffsPhoto/7502.jpg'),
  '7503.jpg': require('../StaffsPhoto/7503.jpg'),
  '7504.jpg': require('../StaffsPhoto/7504.jpg'),

};
export {IMAGE};
